{{- if and .Values.certManager.enabled .Values.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuerName }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  acme:
    server: {{ .Values.certManager.server }}
    email: {{ .Values.certManager.email }}
    privateKeySecretRef:
      name: {{ .Values.certManager.issuerName }}-account-key
    solvers:
    {{- toYaml .Values.certManager.solvers | nindent 4 }}
{{- end }} 
